<script lang="ts">
import Vue from 'vue'
import { Icon as antdIcon } from 'ant-design-vue'

const Icon = antdIcon.createFromIconfontCN({
  scriptUrl: process.env.iconfont as string, // generated by iconfont.cn
}) as any

export default Icon
</script>
